### ISSUE TITLE
Issue with cookies

### ISSUE THREAD

**Issue by SamuraiOndo** [therealmarius/Spotify-2-AppleMusic#22]
Hi, whenever I try to use this program, I always get this issue.  With some troubleshooting, I've narrowed it down to being my cookies but I'm not sure what I should do about it.

`D:\spotify to apple music\Spotify-2-AppleMusic>python3 convertsongs.py my_playlist_87.csv
Traceback (most recent call last):
  File "D:\spotify to apple music\Spotify-2-AppleMusic\convertsongs.py", line 228, in <module>
    create_playlist_and_add_song(argv[1])
  File "D:\spotify to apple music\Spotify-2-AppleMusic\convertsongs.py", line 180, in create_playlist_and_add_song
    playlist_identifier = create_apple_music_playlist(s, playlist_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\spotify to apple music\Spotify-2-AppleMusic\convertsongs.py", line 33, in create_apple_music_playlist
    response = session.get(url)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connectionpool.py", line 497, in _make_request
    conn.request(
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connection.py", line 394, in request
    self.putheader(header, value)
  File "C:\Users\Violet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\urllib3\connection.py", line 308, in putheader
    super().putheader(header, *values)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.240.0_x64__qbz5n2kfra8p0\Lib\http\client.py", line 1292, in putheader
    values[i] = one_value.encode('latin-1')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u20ac' in position 513: ordinal not in range(256)`

**Comment by therealmarius** [comment]
Hi, thanks for reaching out!

It seems that you have a "€" sign somewhere, maybe in your cookies. I've never encountered this issue. I'll try to fix it ASAP.

Best,
@therealmarius

**Comment by therealmarius** [comment]
Hi @SamuraiOndo 

Would you mind checking if there is a `€` sign somewhere in the data you feed to the script ?
If yes, can you please tell me in which it is.

Best,
therealmarius

**Comment by luukvankooten** [comment]
Same issue here, no euro character in my cookie

**Comment by luukvankooten** [comment]
I fixed it to harcode the cookie in side the script and encode it with utf-8

example:

```python
        s.headers.update({"authorization": f"{token}",
                          "media-user-token": f"{media_user_token}",
                          "Cookie": "my cool super long cookie value".encode('utf-8'),
                          "Host": "amp-api.music.apple.com",
                          "Accept-Language": "en-US,en;q=0.5",
                          "Accept": "*/*",
                          "Accept-Encoding": "gzip, deflate, br",
                          "Referer": "https://music.apple.com/",
                          "Origin": "https://music.apple.com",
                          "Content-Length": "45",
                          "Connection": "keep-alive",
                          "Sec-Fetch-Dest": "empty",
                          "Sec-Fetch-Mode": "cors",
                          "Sec-Fetch-Site": "same-site",
                          "DNT": "T"})
```

**Comment by SamuraiOndo** [comment]
> Hi @SamuraiOndo 
> 
> Would you mind checking if there is a `€` sign somewhere in the data you feed to the script ?
> If yes, can you please tell me in which it is.
> 
> Best,
> therealmarius

sorry. meant to reply to this when I saw it, but there was no euro character in my cookies.

**Comment by therealmarius** [comment]
Thanks @luukvankooten I applied your solutions to the code.
If this issue ever come back up, please feel free to reopen this issue or another.

Have fun with your converted playlists,
therealmarius
