### ISSUE TITLE
Exception: Error 401 while creating playlist favs!

### ISSUE THREAD

**Issue by mifune69** [therealmarius/Spotify-2-AppleMusic#26]
```
C:\Users\mifun\Downloads\Spotify-2-AppleMusic-master\Spotify-2-AppleMusic-master>py convertsongs.py favs.csv
Traceback (most recent call last):
  File "C:\Users\mifun\Downloads\Spotify-2-AppleMusic-master\Spotify-2-AppleMusic-master\convertsongs.py", line 228, in <module>
    create_playlist_and_add_song(argv[1])
  File "C:\Users\mifun\Downloads\Spotify-2-AppleMusic-master\Spotify-2-AppleMusic-master\convertsongs.py", line 180, in create_playlist_and_add_song
    playlist_identifier = create_apple_music_playlist(s, playlist_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mifun\Downloads\Spotify-2-AppleMusic-master\Spotify-2-AppleMusic-master\convertsongs.py", line 44, in create_apple_music_playlist
    raise Exception(f"Error {response.status_code} while creating playlist {playlist_name}!")
Exception: Error 401 while creating playlist favs!
```

dude pls help me

**Comment by therealmarius** [comment]
Hi! Thanks for reaching out.

Error 401 means that the action was not authorized by the system (in that case, Apple Music servers).
Please check all the connection data. They are case sensitive.

Please try again and let me know if you've been able to resolve the issue.

Best,
therealmarius

**Comment by therealmarius** [comment]
Since there's been no update on the issue for over a week, I'll assume that the issue is resolved.
